/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Order = IDL.Record({
  'url' : IDL.Text,
  'status' : OrderStatus,
  'owner' : IDL.Principal,
  'package' : IDL.Text,
  'createdAt' : IDL.Int,
  'orderId' : IDL.Nat,
  'price' : IDL.Nat,
  'packageId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrderWithWallet' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'adminDistributeFunds' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'adminTopUp' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getAdminWalletBalanceForAdminNavBar' : IDL.Func([], [IDL.Nat], ['query']),
  'getAdminWalletBalanceLegacy' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getBalanceForAdminSidebar' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getUserBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'onboarding' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Order = IDL.Record({
    'url' : IDL.Text,
    'status' : OrderStatus,
    'owner' : IDL.Principal,
    'package' : IDL.Text,
    'createdAt' : IDL.Int,
    'orderId' : IDL.Nat,
    'price' : IDL.Nat,
    'packageId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrderWithWallet' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'adminDistributeFunds' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'adminTopUp' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getAdminWalletBalanceForAdminNavBar' : IDL.Func([], [IDL.Nat], ['query']),
    'getAdminWalletBalanceLegacy' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getBalanceForAdminSidebar' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getUserBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'onboarding' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };