/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'url' : string,
  'status' : OrderStatus,
  'owner' : Principal,
  'package' : string,
  'createdAt' : bigint,
  'orderId' : bigint,
  'price' : bigint,
  'packageId' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface UserProfile {
  'bio' : [] | [string],
  'username' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
  'profilePicture' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrderWithWallet' : ActorMethod<[string, bigint, string, bigint], bigint>,
  'adminDistributeFunds' : ActorMethod<[Principal, bigint], undefined>,
  'adminTopUp' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminWalletBalance' : ActorMethod<[], bigint>,
  'getAdminWalletBalanceForAdminNavBar' : ActorMethod<[], bigint>,
  'getAdminWalletBalanceLegacy' : ActorMethod<[], bigint>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getBalanceForAdminSidebar' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderById' : ActorMethod<[bigint], [] | [Order]>,
  'getUserBalance' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'onboarding' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];